import { HelloServer } from '@button-poc/components/server';
import './global.css';

export const metadata = {
  title: 'Welcome to button',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HelloServer />
        {children}
      </body>
    </html>
  );
}
